name: Config Distro Ignore
type: module
description: Retain custom configuration when importing the distribution configuration.
core_version_requirement: ^8.8 || ^9
package: Config
dependencies:
  - config_distro:config_distro
  - config_distro:config_distro_filter

# Information added by Drupal.org packaging script on 2020-06-18
version: '8.x-1.0-alpha4'
project: 'config_distro'
datestamp: 1592523912
