# Schema for the configuration files of the confirm registration email module.

reg_confirm_email.settings:
  type: config_object
  label: 'reg_confirm_email settings'
  mapping:
    mail_confirm:
      type: boolean
    mail_desc:
      type: string
