name: Config Distro Filter
type: module
description: "Bridge between Config Filter and Config Distro's use of Transform API to keep backwards compatibility."
package: Config
core_version_requirement: ^8.8 || ^9
dependencies:
  - config_distro:config_distro
  - config_filter:config_filter

# Information added by Drupal.org packaging script on 2020-06-18
version: '8.x-1.0-alpha4'
project: 'config_distro'
datestamp: 1592523912
