services:

  config_normalizer.normalizer:
    class: Drupal\config_normalizer\ConfigNormalizer
    arguments:
      - "@config.typed"

  # deprecated
  plugin.manager.config_normalizer:
    class: Drupal\config_normalizer\Plugin\ConfigNormalizerManager
    parent: default_plugin_manager
