name: 'Config Merge Filter'
type: module
description: "Provides a Config Filter plugin that safely merges configuration updates into the site's active configuration."
core: 8.x
core_version_requirement: ^8 || ^9
package: Configuration
dependencies:
 - config_merge:config_merge
 - config_filter:config_filter

# Information added by Drupal.org packaging script on 2022-09-29
version: '8.x-1.0'
project: 'config_merge'
datestamp: 1664456521
