name: Config Distro
type: module
description: Framework for managing configuration updates from distributions.
core_version_requirement: ^8.8 || ^9
package: Config
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2020-06-18
version: '8.x-1.0-alpha4'
project: 'config_distro'
datestamp: 1592523912
