name: 'Configuration Provider'
type: module
description: 'Enables provision of configuration by extensions.'
core: 8.x
core_version_requirement: ^8 || ^9
package: Config
dependencies:
 - 'drupal:config'

# Information added by Drupal.org packaging script on 2020-06-23
version: '8.x-2.0-rc4'
project: 'config_provider'
datestamp: 1592923706
