user_restrictions.user_restrictions.*:
  type: config_entity
  label: 'User restrictions'
  mapping:
    name:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    pattern:
      type: string
      label: 'Pattern'
    access_type:
      type: boolean
      label: 'Access type'
    rule_type:
      type: string
      label: 'Restriction type'
    expiry:
      type: integer
      label: 'Expiration'
