_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  content_editor: 3
  administrator: 4
  subscriber: 5
content_access_node_type:
  dashboard: 'a:2:{s:8:"view_own";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}s:4:"view";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}}'
