smtp_host: mail.firjan-fp.cityconnect.com.br
smtp_hostbackup: ''
smtp_port: 465
smtp_protocol: ssl
smtp_username: noreply@firjan-ml.cityconnect.com.br
smtp_password: 'Nr++3s&03gOR'
smtp_authentication_type: basic_auth
smtp_fromname: 'Firjan + Mercado Livre'
smtp_always_replyto: true
smtp_keepalive: false
smtp_debug: 4
smtp_debug_log: false
smtp_ssl_verify_peer: true
smtp_ssl_verify_peer_name: true
smtp_ssl_allow_self_signed: true
smtp_envelope_sender_option: other
smtp_envelope_sender: noreply@firjan-ml.cityconnect.com.br
smtp_ehlo_host: ''
smtp_timeout: null
