_core:
  default_config_hash: 5ZGgXY2ZsTeL35alMtkeWZzDTiT2VwezldOyiiFkOCU
cache: false
sourcemaps: true
output_format: compressed
flush_cache_type: default
check_modify_time: true
node_modules_path: ''
plugins:
  scss: scss_compiler_scssphp
